name: cumming-group

services:
  wordpress:
    build: .
    ports:
      - "80:80"
    environment:
      WORDPRESS_DEBUG: true
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${PWD}/public_html:/var/www/html
      - ${PWD}/config/docker-php.ini:/usr/local/etc/php/conf.d/docker.ini

    depends_on:
      - wp_db

  wp_db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword

volumes:
  db_data: